version: '3.8'

services:
  multi_rag_api:
    build: .
    container_name: multi-provider-rag
    ports:
      - "8000:8000"
    volumes:
      - ./chromadb_store:/app/chromadb_store
      - ./data:/app/data
      - ./upload_files:/app/upload_files
    env_file:
      - .env
    environment:
      - DEFAULT_EMBEDDING_PROVIDER=azure
      - DEFAULT_LLM_PROVIDER=azure
    restart: unless-stopped
    command: >
      uvicorn api.multi_provider_rag_api:app
      --host 0.0.0.0
      --port 8000
